# Hexadecimal addresses/values will be converted to binary by Python, so keep them as
# strings so they come out as hex in the generated code.

# Base address of the accelerator
baseaddr: "0x43c10000"
# Size of the accelerator register space, bytes
regwidth: "0x13"
# Size of the tap register space, bytes
tapwidth: "0x10"

registers:
  run: "0x00"

instreams:
  input0:
    dma_addr: "0x40400000"
    width: 1454
    height: 974
    irq: 61


outstreams:
  output:
    dma_addr: "0x40400030"
    width: 720
    height: 480
    irq: 62


