# Hexadecimal addresses/values will be converted to binary by Python, so keep them as
# strings so they come out as hex in the generated code.

# Base address of the accelerator
baseaddr: "0x43c10000"
# Size of the accelerator register space, bytes
regwidth: "0x1a4"
# Interrupt for the VDMA (xilcam) engine
vdma_irq: 63

registers:
  run: "0x00"

instreams:
  input0:
    dma_addr: "0x40400000"
    width: 264
    height: 264
    irq: 61


outstreams:
  output:
    dma_addr: "0x40400030"
    width: 256
    height: 256
    irq: 62


