# Hexadecimal addresses/values will be converted to binary by Python, so keep them as
# strings so they come out as hex in the generated code.

# Base address of the accelerator
baseaddr: "0x7de00000"
# Size of the accelerator register space, bytes
regwidth: "0x13"
# Size of the tap register space, bytes
tapwidth: "0x10"

registers:
  run: "0x00"

instreams:
  input0:
    dma_addr: "0x40400000"
    width: 258
    height: 258
    irq: 61
  input1:
    dma_addr: "0x40410000"
    width: 16
    height: 16
    irq: 62

outstreams:
  output:
    dma_addr: "0x40400030"
    width: 256
    height: 256
    irq: 63


